apiVersion: v1
kind: Pod
metadata:
  name: ci
  namespace: jenkins
spec:
  containers:
    - name: main
      image: registry.milvus.io/devops/cd-base:20220316-a7c2c5e
      args: ["cat"]
      resources:
        requests:
          cpu: "10"
          memory: 5Gi
      tty: true
    - name: kaniko
      imagePullPolicy: IfNotPresent
      image: registry.milvus.io/devops/kaniko-executor:v1.8.0-debug
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
  volumes:
    - name: kaniko-secret
      secret:
        secretName: registry-milvus-io
        items:
          - key: .dockerconfigjson
            path: config.json