name: Base Image (Ubuntu 20.04 + OpenBLAS 0.3.20)

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'base*'
    paths:
      - 'docker/base/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: docker/base/Dockerfile
          context: .
          build-args: OPENBLAS=0.3.20
          platforms: linux/amd64,linux/arm64
          push: true
          tags: soulteary/milvus-base:ubuntu20.04-openblas0.3.20