name: ESS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -
        name: builder
        uses: docker/build-push-action@v3
        with:
          file: docker/builder/Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: janej2013/milvus:builder-ubuntu20.04-openblas0.3.20-golang1.18
      -
        name: app
        uses: docker/build-push-action@v3
        with:
          file: docker/app/Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: janej2013/milvus-ess:v2.2.3
